{
    "description": "A Python exception",
    "properties": {
        "exc": {
            "description": "Message from extracted traceback (should be identical to `message`)",
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "null"
                }
            ]
        },
        "fname": {
            "description": "Name of file from which the exception was thrown",
            "type": "string"
        },
        "func": {
            "description": "Name of function from which the exception was thrown",
            "type": "string"
        },
        "line_number": {
            "description": "Line at which exception occurred",
            "type": "number"
        },
        "message": {
            "description": "Message passed to exception",
            "type": "string"
        }
    },
    "required": [
        "message"
    ],
    "title": "Error",
    "type": "object"
}